apiVersion: v1
kind: Namespace
metadata:
  name: guard-onboarding
---
apiVersion: v1
kind: Secret
metadata:
  name: guard-onboarding
  namespace: guard-onboarding
data:
  TENANT_ID: Y2YxODZkYWQtZTJiMS00MGZhLTg2MzctZTg4ZWU2ZjJmMmNj
  SUBSCRIPTION_ID: ODdlODZmZjYtZTU3Zi00Yzg4LWI2NWUtODM1YWQ3NzgyN2Jm
  RESOURCE_GROUP: Y29ubmVjdGVkQ2x1c3Rlcg==
  CONNECTED_CLUSTER: Y29ubmVjdGVkQ2x1c3Rlcg==
  LOCATION: ZWFzdHVz
  CLIENT_ID: Y2Y0YjJhNjMtYTIxMS00ZGY2LWFmNzEtNGU0ZjI5NGU4YTNm
  CLIENT_SECRET: R35YLjRScUxfVEVjMTF+SGV+ZEJmLkQ0SlltTFg5R2ZuMw==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guard-onboarding
  namespace: guard-onboarding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guard-onboarding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: guard-onboarding
    namespace: guard-onboarding
---
apiVersion: batch/v1
kind: Job
metadata:
  name: guard-onboarding
  namespace: guard-onboarding
spec:
  template:
    spec:
      volumes:
      - name: guard-manifests
        hostPath:
          path: /etc/guard
          type: DirectoryOrCreate
      serviceAccountName: guard-onboarding
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: guard-onboarding
        image: delanyo32/guard-onboarding:latest
        volumeMounts:
        - name: guard-manifests
          mountPath: /etc/guard
        env:
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: TENANT_ID
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: SUBSCRIPTION_ID
        - name: RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: RESOURCE_GROUP
        - name: CONNECTED_CLUSTER
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: CONNECTED_CLUSTER
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: LOCATION
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: guard-onboarding
              key: CLIENT_SECRET
      restartPolicy: Never
  backoffLimit: 4
