apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ds-secret
  namespace: kube-system
data:
  RESOURCE_GROUP: {{ required "Resource Group is required" .Values.resourceGroup | b64enc }}
  TENANT_ID: {{ required "Tenant Id is required" .Values.tenantId | b64enc }}
  CLIENT_ID: {{ required "Client Id is required" .Values.clientId | b64enc }}
  CLIENT_SECRET: {{ required "Client Secret is required" .Values.clientSecret | b64enc }}
  KEYVAULT_NAME: {{ required "Keyvault name is required" .Values.keyvaultName | b64enc }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-ds
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      - operator: "Exists"
        effect: NoExecute
      - operator: "Exists"
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/role: master
        kubernetes.io/os: linux
      containers:
      - name: master-config
        image: {{ .Values.demonsetImage }}
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        env:
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-ds-secret
              key: TENANT_ID
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-ds-secret
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-ds-secret
              key: CLIENT_SECRET
        - name: RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-ds-secret
              key: RESOURCE_GROUP
        - name: KEYVAULT_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-ds-secret
              key: KEYVAULT_NAME
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes